//@flow
const Actions = {
  ADD_SCENARIO_NAME: 'ADD_SCENARIO_NAME',
  ADD_THING: 'ADD_THING',
  REMOVE_THING: 'REMOVE_THING',
  ADD_STATE: 'ADD_STATE',
  EDIT_STATE: 'EDIT_STATE',
  ADD_TRANSITION: 'ADD_TRANSITION',
};
export default Actions;
